library(shiny)
library(shinydashboard)        
library(nortest)
library(mvnormtest)
library(MASS)
library(shinyLP)
library(class)
library(gmodels)
library(caret)
library(rattle)
library(ranger)
library(klaR)
library(kernlab)
library(micad)
library(e1071)
library(NeuralNetTools)
library(neuralnet)
library(nnet)
library(mclust)



